version: "3.9"
services:
  frontend:
    build: ./frontend
    ports: ["8080:8080"]
    depends_on: [api]
  
  api:
    build: ./backend/api
    env_file: ./backend/.env
    ports: ["8000:8000"]
    depends_on: [redis, postgres]

  worker:
    build: ./backend/worker
    env_file: .env
    depends_on: [redis, postgres]

  redis:
    image: redis:7

  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
