version: "3.9"
services:
  frontend:
    build: ./frontend
    ports: ["8080:8080"]
    depends_on: [api]
  
  api:
    build: ./backend/api
    env_file: ./backend/.env
    ports: ["8000:8000"]
    depends_on: 
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  worker:
    build: ./backend/worker
    env_file: ./backend/.env
    depends_on: 
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  redis:
    image: redis:7

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
